### ISSUE TITLE
where txt.py is located in the haystack package.  Thanks!

### ISSUE THREAD

**Issue by tonhsiao** [mc112611/haystack-chinese#1]
請問 txt.py 位於哪個目錄下, 我只更新preporcessor.py, 執行結果仍是一樣, jieba分詞似乎沒有作用.

>>> document_store.write_documents(preprocessed_docs)
Document id fd299c469545782dabd608ae89d325b2 is not in uuid format. Such ids will be replaced by uuids, in this case 317bba2c-6d85-9e11-2050-7afb766c7faa.
No embedding found in Document object being written into Weaviate. A dummy embedding is being supplied so that indexing can still take place. This embedding should be overwritten in order to perform vector similarity searches

**Comment by mc112611** [comment]
txt.py目录在：你的解释器环境\Lib\site-packages\haystack\nodes\file_converter中。

如果使用官方教程中的内容。其使用的文本相似度模型，不是中文的。因此你需要找中文的embedding模型，以及中文的QA模型。

详情在：https://zhuanlan.zhihu.com/p/670097450      我会持续更新。   里面有代码，直接复制粘贴即可

**Comment by mc112611** [comment]
很多问题，以及细节，我会在后续的文章中更新。请先根据我的文章中的内容部署操作。后续我会提供一些实用性的接口参数解释，以及优化的教程。    如果有时间，建议研究一下官方接口文档，以及官方使用文档，里面的注释非常详细，开发组对这个项目，完全是抱着教会大家如何使用为目的。             如果您是中国香港，中国台湾地区的兄弟，我不确定在繁体中文上，jieba分词的效果会有保证。    如果有这方面的问题，我会提供我修改的思路。          请等待下周左右，第四个文章的更新。  届时，我会在该github主页进行更新README.md文件

**Comment by tonhsiao** [comment]
非常感謝您的回覆, 沒錯, 我的文檔是繁體中文. (來自台灣, 但不是兄弟)
Embedding Model: gte-large-zh, 
QA Model: Yi-6B-200K-GGUF
在更換preprocesser.py和txt.py後, 結果仍是一樣, 如下.
>>> document_store.write_documents(preprocessed_docs)
Document id 22ab37291036181190a51eb9e1652cdd is not in uuid format. Such ids will be replaced by uuids, in this case 6307551f-1fc8-9c12-d910-50458ec63d00.
No embedding found in Document object being written into Weaviate. A dummy embedding is being supplied so that indexing can still take place. This embedding should be overwritten in order to perform vector similarity searches.
10000it [00:00, 128143.91it/s]

謝謝您!

**Comment by mc112611** [comment]
看上去似乎是数据库方面的问题。   很遗憾，这个问题我没有遇到过。 可以去官方项目问一下。https://github.com/deepset-ai/haystack

**Comment by tonhsiao** [comment]
> 看上去似乎是数据库方面的问题。 很遗憾，这个问题我没有遇到过。 可以去官方项目问一下。https://github.com/deepset-ai/haystack

還是謝謝您! 至少有個方向了.

**Comment by tonhsiao** [comment]
> 看上去似乎是数据库方面的问题。 很遗憾，这个问题我没有遇到过。 可以去官方项目问一下。https://github.com/deepset-ai/haystack

以下是文檔preprocessed_docs 的結果, 繁體中文使用jieba分詞, 是否不合適
還是我的設定有問題....
```
preprocessor = PreProcessor(
    clean_empty_lines=True,
    clean_whitespace=False,
    clean_header_footer=True,
    split_by="word",
    split_length=2,
    split_respect_sentence_boundary=False,
)
preprocessed_docs = preprocessor.process(final_doc)
print("Preprocessed Docs: ", preprocessed_docs)
以下是結果:
8ca9'}>, <Document: {'content': 'L4、', 'content_type': 'text', 'score': None, 'meta': {'_split_id': 1681},
['content'], 'embedding': None, 'id': '95c256bd70b9f6a21f1dbd26fb12271e'}>, <Document: {'content': '該群組' 'text', 'score': None, 'meta': {'_split_id': 1682}, 'id_hash_keys': ['content'], 'embedding': None, 'id': 67b227d5be1217fe'}>, <Document: {'content': ' L3', 'content_type': 'text', 'score': None, 'meta': {'_split_ash_keys': ['content'], 'embedding': None, 'id': 'bb1695955f5c5a0a17f211a18571999a'}>, <Document: {'contentnt_type': 'text', 'score': None, 'meta': {'_split_id': 1684}, 'id_hash_keys': ['content'], 'embedding': Non225e157cb7e04e42bd8c62774'}>, <Document: {'content': '群組 ', 'content_type': 'text', 'score': None, 'meta'685}, 'id_hash_keys': ['content'], 'embedding': None, 'id': '5d2ca7aabe580e1795562bf6a8ef55c9'}>, <Document。', 'content_type': 'text', 'score': None, 'meta': {'_split_id': 1686}, 'id_hash_keys': ['content'], 'embe': '7711e40e67668acb000adc32aba68a2d'}>, <Document: {'content': ' \n', 'content_type': 'text', 'score': Nonit_id': 1687}, 'id_hash_keys': ['content'], 'embedding': None, 'id': 'bf9adb60bae296da9aade42262315a03'}>, ent': ' ', 'content_type': 'text', 'score': None, 'meta': {'_split_id': 1688}, 'id_hash_keys': ['content'],e, 'id': '3fd44c9b7c437cb818f081109e84f739'}>]
```

**Comment by mc112611** [comment]
首先我也查了一下，jeiba分词是支持繁体中文的。参考文章：https://zhuanlan.zhihu.com/p/361052986

在上面你提供的代码中，参数 split_length 代表着，你想要将大文档切分成为以n个词为一个的小文档。如果设置为2，则代表2个词。因为英文的按照word切分，直接空格切分就可以，但是中文借助了jieba工具。jieba分词之后，有的词语是2个字符组成，有的词语甚至可以是四个字的成语。    

因为我不知道你输入的原句子是什么样子的。     我觉得你可以试着调整split_length，一般设置为200或者300左右，切割后的小文档，大约在400到600个字符之间。   preprocessor类，将大文档切分为小文档，实际上是为了照顾embedding模型的输入长度。  假如embedding模型的输入长度限制在512 。而原始文档是好几万字。 这时候就要做预处理长文档了。     

一个小tips，  split_respect_sentence_boundary 这个参数建议设置为True。它会防止每个小文档的最后一句话只说了一半就被按照词数量截断，会保证最后一句话是一个完整的句子

**Comment by tonhsiao** [comment]
謝謝您幫忙點出問題, 
不好意思, 想請教您, 以下問題:
1. 這個程式haystack的RAG, 似乎是擷取文件中的片斷文字, 僅將其呈現
卻不是消化過文件的文字, Model用自己的話說出來
haystack是否可以設定temperature?

2. 不知您可否推薦的github程式可以參考...
我是從這裏參考作法的. 
https://github.com/AIAnytime/Haystack-and-Mistral-7B-RAG-Implementation

```
def initialize_model():
    return PromptModel(
#            model_name_or_path="model/Yi-6B-200K-GGUF/yi-6b-200k.Q5_K_S.gguf",
        model_name_or_path="model/Mistral-7B-Instruct-v0.1-GGUF/mistral-7b-instruct-v0.1.Q5_K_M.gguf",
        invocation_layer_class=LlamaCPPInvocationLayer,
        use_gpu=True, #False
        max_length=1024 #512
    )

class PromptNode(
    model_name_or_path: str | PromptModel = "google/flan-t5-base",
    default_prompt_template: str | PromptTemplate | None = None,
    output_variable: str | None = None,
    max_length: int | None = 100,
    api_key: str | None = None,
    use_auth_token: str | bool | None = None,
    use_gpu: bool | None = None,
    devices: List[str | device] | None = None,
    stop_words: List[str] | None = None,
    top_k: int = 1,
    debug: bool | None = False,
    model_kwargs: Dict | None = None
)
```

**Comment by mc112611** [comment]
看上去这似乎使用了hastack+openAI的大模型做的一个大模型外挂知识库的解决方案。并使用了fastAPI进行部署服务。  实际上，haystack官方文档里有这类教程，比如https://docs.haystack.deepset.ai/docs/agent

如果你想用本地部署的LLM，我可以提供一个思路，你可以将haystack检索结果的top-k个结果，输入进大模型，写好提示模板，让大模型组织语言，分析检索结果，以及用户输入进的问题，去回答问题
