### ISSUE TITLE
请求支持2.0版本

### ISSUE THREAD

**Issue by zhanggc2019** [mc112611/haystack-chinese#2]
有计划支持2.0吗

**Comment by mc112611** [comment]
> 有计划支持2.0吗

这是一个好问题。

请看官方项目的[这个脚本](https://github.com/deepset-ai/haystack/blob/c682a59f5e5569c65fd3427470ab51116df438d2/haystack/components/preprocessors/document_splitter.py#L126)

在第126行，这个函数，你应该可以自行修改切分的方法。

也许是官方收到了很多兼容语种的问题，因此在2.0版本官方舍弃了nltk，用了更简单的嵌套实现这个功能。 （至少暂时是这样）
