### ISSUE TITLE
佬，你的数据链接失效了

### ISSUE THREAD

**Issue by aonoa** [mc112611/haystack-chinese#3]
![image](https://github.com/user-attachments/assets/5e415227-7996-4e41-9a6a-bb5af6d71f4e)
这个数据能否给我发送一份，我想实际测试一下2.0的效果，然后去提issue

**Comment by mc112611** [comment]
已更新
wiki百科词条，里面包含了一些敏感关键字，被度盘屏蔽了。

测试用数据data_test

链接：https://pan.baidu.com/s/10HPre8BcaUZDyZ3_wsakMg?pwd=znx6 
提取码：znx6
解压密码：1234

完整数据：
链接：https://pan.baidu.com/s/1PtCAjOTfpAXWVozoOMhP-A?pwd=c2g4 
提取码：c2g4
解压密码：1234

**Comment by aonoa** [comment]
密码好像不太对
![image](https://github.com/user-attachments/assets/e178613a-81b6-4051-945f-d38fe6248bc7)

**Comment by mc112611** [comment]
我自己试了一下解压密码，是没问题的。  两个压缩文件解压码都是1234。我使用的是winrar压缩的。 

另一个办法：你可以尝试一下找中文wiki数据集。并把格式也变成：每个词条一个txt文件。

**Comment by aonoa** [comment]
好的，感谢大佬，我换了台win电脑成功解压了
